# Generated by Django 4.2.23 on 2025-08-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_lat_post_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subdivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_number', models.CharField(max_length=50, unique=True)),
                ('is_occupied', models.BooleanField(default=False)),
                ('owner_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
