# Generated by Django 4.2.23 on 2025-08-22 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
