# Generated by Django 4.2.23 on 2025-08-26 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_facility_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('Court', 'Basketball Court'), ('Pool', 'Swimming Pool')], max_length=100),
        ),
    ]
