# Generated by Django 4.2.23 on 2025-08-26 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_facility_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facility',
            name='pin',
        ),
    ]
