# Generated by Django 5.2.5 on 2025-10-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alert_contactinfo_contactmessage_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='pin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='occupant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='price',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
