# Generated by Django 4.2.23 on 2025-11-05 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_residentpin_pin_historicalresidentpin'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitor',
            name='pin_entered',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='pin_entered',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.residentpin'),
        ),
    ]
