# Generated by Django 4.2.23 on 2025-11-05 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_historicalvisitor_pin_entered_visitor_pin_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresidentpin',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvisitor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalvisitor',
            name='pin_entered',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='residentpin',
            name='pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='pin_entered',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='resident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='api.residentpin'),
        ),
    ]
