# Generated by Django 4.2.23 on 2025-11-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_allowedemail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllowedEmail',
        ),
    ]
