# Generated by Django 4.2.23 on 2025-11-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_historicalvisitor_gmail_visitor_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalvisitor',
            name='gmail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='gmail',
            field=models.EmailField(default='default@example.com', max_length=254),
        ),
    ]
