# Generated by Django 4.2.23 on 2025-11-12 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_alter_historicalvisitor_gmail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalVisitor',
        ),
    ]
