# Generated by Django 4.2.23 on 2025-11-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_delete_historicalvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
