# Generated by Django 4.2.23 on 2025-11-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_visitor_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
