# Generated by Django 4.2.23 on 2025-11-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_historicalvisitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpin',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpin',
            name='square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pin_images/'),
        ),
        migrations.AddField(
            model_name='pin',
            name='square_meter',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
