# Generated by Django 4.2.23 on 2025-11-17 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0036_house_owner_alter_house_address_alter_house_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='house',
            name='owner',
        ),
        migrations.AddField(
            model_name='house',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='house',
            name='contact',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='house',
            name='description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='houses/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
