# Generated by Django 4.2.23 on 2025-11-17 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0037_remove_house_owner_house_user_alter_house_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='address',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='house',
            name='contact',
        ),
        migrations.AlterField(
            model_name='house',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='house_images/'),
        ),
        migrations.AlterField(
            model_name='house',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
