# Generated by Django 4.2.23 on 2025-11-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_alter_house_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluserprofile',
            name='billing',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='billing',
            field=models.FileField(blank=True, null=True, upload_to='billing/'),
        ),
    ]
