# Generated by Django 4.2.23 on 2025-11-22 05:10

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0042_historicalbillingrecord_billingrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_image', models.ImageField(blank=True, help_text='Bill image uploaded by admin', null=True, upload_to=api.models.service_fee_bill_path)),
                ('receipt_image', models.ImageField(blank=True, help_text='Receipt image uploaded by homeowner', null=True, upload_to=api.models.service_fee_receipt_path)),
                ('policy_image', models.ImageField(blank=True, help_text='Policy document/image uploaded by admin', null=True, upload_to=api.models.service_fee_policy_path)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Service fee amount', max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due date for payment', null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delayed', 'Delayed')], default='unpaid', max_length=10)),
                ('month', models.CharField(blank=True, help_text='Billing month (e.g., January 2024)', max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Billing year', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or description', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('homeowner', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='service_fees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Fee',
                'verbose_name_plural': 'Service Fees',
                'ordering': ['-created_at', '-due_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalServiceFee',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('bill_image', models.TextField(blank=True, help_text='Bill image uploaded by admin', max_length=100, null=True)),
                ('receipt_image', models.TextField(blank=True, help_text='Receipt image uploaded by homeowner', max_length=100, null=True)),
                ('policy_image', models.TextField(blank=True, help_text='Policy document/image uploaded by admin', max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Service fee amount', max_digits=10, null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due date for payment', null=True)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('delayed', 'Delayed')], default='unpaid', max_length=10)),
                ('month', models.CharField(blank=True, help_text='Billing month (e.g., January 2024)', max_length=20, null=True)),
                ('year', models.IntegerField(blank=True, help_text='Billing year', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or description', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('homeowner', models.ForeignKey(blank=True, db_constraint=False, limit_choices_to={'is_staff': False}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Service Fee',
                'verbose_name_plural': 'historical Service Fees',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalFAQ',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.IntegerField(default=0, help_text='Order for display (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical FAQ',
                'verbose_name_plural': 'historical FAQs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
