# Generated by Django 4.2.23 on 2025-11-23 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_faq_servicefee_historicalservicefee_historicalfaq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluserprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
