# Generated by Django 4.2.23 on 2025-11-26 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_maintenance_historicalmaintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='name',
            field=models.CharField(choices=[('Court', 'Basketball Court'), ('Pool', 'Swimming Pool'), ('Clubhouse', 'Clubhouse')], max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalfacility',
            name='name',
            field=models.CharField(choices=[('Court', 'Basketball Court'), ('Pool', 'Swimming Pool'), ('Clubhouse', 'Clubhouse')], max_length=100),
        ),
    ]
