# Generated by Django 4.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_facility_name_alter_historicalfacility_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'For Sale'), ('rent', 'For Rent')], default='sale', max_length=10),
        ),
    ]

