# Generated by Django 4.2.23 on 2025-11-27 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0051_historicalcommunitymedia_communitymedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_contact_number', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for visit', null=True)),
                ('one_time_pin', models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True)),
                ('visit_date', models.DateField()),
                ('visit_start_time', models.TimeField()),
                ('visit_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('used', 'Used')], default='pending_admin', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, help_text='Reason for decline (if applicable)', null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file_path', models.FileField(blank=True, null=True, upload_to='visitor_request_pdfs/')),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_visitor_requests', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_requests', to=settings.AUTH_USER_MODEL)),
                ('visitor_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_request', to='api.visitor')),
            ],
            options={
                'verbose_name': 'Visitor Request',
                'verbose_name_plural': 'Visitor Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVisitorRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=255)),
                ('visitor_email', models.EmailField(max_length=254)),
                ('visitor_contact_number', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, help_text='Reason for visit', null=True)),
                ('one_time_pin', models.CharField(blank=True, db_index=True, max_length=6, null=True)),
                ('visit_date', models.DateField()),
                ('visit_start_time', models.TimeField()),
                ('visit_end_time', models.TimeField()),
                ('status', models.CharField(choices=[('pending_admin', 'Pending Admin Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('expired', 'Expired'), ('used', 'Used')], default='pending_admin', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, help_text='Reason for decline (if applicable)', null=True)),
                ('pdf_generated', models.BooleanField(default=False)),
                ('pdf_file_path', models.TextField(blank=True, max_length=100, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('visitor_record', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.visitor')),
            ],
            options={
                'verbose_name': 'historical Visitor Request',
                'verbose_name_plural': 'historical Visitor Requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
