# Generated by Django 4.2.23 on 2025-11-28 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_visitorrequest_historicalvisitorrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitorrequest',
            name='visit_end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day visits (optional - if not set, uses visit_date)', null=True),
        ),
        migrations.AddField(
            model_name='visitorrequest',
            name='visit_end_date',
            field=models.DateField(blank=True, help_text='End date for multi-day visits (optional - if not set, uses visit_date)', null=True),
        ),
    ]
