# Generated by Django 4.2.23 on 2025-11-28 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_historicalvisitorrequest_visit_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='amenities',
            field=models.TextField(blank=True, help_text='Comma-separated list of amenities', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='association_dues',
            field=models.CharField(blank=True, help_text='Association dues information', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='baths',
            field=models.IntegerField(default=0, help_text='Number of bathrooms'),
        ),
        migrations.AddField(
            model_name='house',
            name='beds',
            field=models.IntegerField(default=0, help_text='Number of bedrooms'),
        ),
        migrations.AddField(
            model_name='house',
            name='days_on_market',
            field=models.CharField(blank=True, help_text="Days on the market (e.g., '1 month', '2 weeks')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='floor_area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Floor area in square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='furnishing',
            field=models.CharField(blank=True, choices=[('fully_furnished', 'Fully Furnished'), ('semi_furnished', 'Semi Furnished'), ('unfurnished', 'Unfurnished')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='house_images/')),
                ('order', models.IntegerField(default=0, help_text='Order for displaying images')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.house')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('house', 'order')},
            },
        ),
    ]
