# Generated by Django 4.2.23 on 2025-11-28 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0054_house_amenities_house_association_dues_house_baths_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Advance payment amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='deposit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Security deposit amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='down_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Required down payment', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='floors',
            field=models.IntegerField(default=1, help_text='Number of floors/stories'),
        ),
        migrations.AddField(
            model_name='house',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_security',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='lease_term',
            field=models.CharField(blank=True, help_text="Lease term (e.g., '1 year', '6 months')", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='lot_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lot size in square meters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='nearby_facilities',
            field=models.TextField(blank=True, help_text='Nearby schools, malls, hospitals, etc.', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='parking_spaces',
            field=models.IntegerField(default=0, help_text='Number of parking spaces'),
        ),
        migrations.AddField(
            model_name='house',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Payment terms and conditions', null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='pet_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='property_status',
            field=models.CharField(default='available', help_text='Property status: available, pending, sold, rented', max_length=20),
        ),
        migrations.AddField(
            model_name='house',
            name='property_type',
            field=models.CharField(blank=True, choices=[('house', 'House'), ('apartment', 'Apartment'), ('condo', 'Condo'), ('townhouse', 'Townhouse'), ('villa', 'Villa'), ('duplex', 'Duplex'), ('studio', 'Studio')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='house',
            name='utilities_included',
            field=models.BooleanField(default=False, help_text='Are utilities included in the price?'),
        ),
        migrations.AddField(
            model_name='house',
            name='year_built',
            field=models.IntegerField(blank=True, help_text='Year the property was built', null=True),
        ),
        migrations.DeleteModel(
            name='HouseImage',
        ),
    ]
