# Generated by Django 4.2.23 on 2025-11-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0056_houseimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='has_air_conditioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_cable_tv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_clubhouse',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_dishwasher',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_dryer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_fireplace',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_garage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_generator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_heating',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_intercom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_laundry_room',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_microwave',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_playground',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_refrigerator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_solar_panels',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_storage',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_washing_machine',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_water_heater',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='house',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
    ]
