# Generated by Django 4.2.16 on 2025-12-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0061_historicalpost_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('carpenter', 'Carpenter'), ('aircon', 'Air Conditioning Repair'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roofing', 'Roofing'), ('renovation', 'House Renovation'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('appliance', 'Appliance Repair'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the maintenance needed')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('use_external_contractor', models.BooleanField(default=False, help_text='If homeowner wants to call someone outside the subdivision')),
                ('external_contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_contractor_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('external_contractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_maintenance_requests', to=settings.AUTH_USER_MODEL)),
                ('homeowner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Maintenance Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaintenanceRequest',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('carpenter', 'Carpenter'), ('aircon', 'Air Conditioning Repair'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roofing', 'Roofing'), ('renovation', 'House Renovation'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('appliance', 'Appliance Repair'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the maintenance needed')),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('is_urgent', models.BooleanField(default=False)),
                ('use_external_contractor', models.BooleanField(default=False, help_text='If homeowner wants to call someone outside the subdivision')),
                ('external_contractor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('external_contractor_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('external_contractor_company', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('declined_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('homeowner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical maintenance request',
                'verbose_name_plural': 'historical Maintenance Requests',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
