# Generated by Django 4.2.16 on 2025-12-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0062_maintenancerequest_historicalmaintenancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitorrequest',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, help_text='Vehicle plate number (if applicable)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='visitorrequest',
            name='vehicle_plate_number',
            field=models.CharField(blank=True, help_text='Vehicle plate number (if applicable)', max_length=20, null=True),
        ),
    ]
