# Generated by Django 4.2.16 on 2025-12-01 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0063_historicalvisitorrequest_vehicle_plate_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmaintenancerequest',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Admin notes or feedback on the maintenance request', null=True),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='admin_feedback',
            field=models.TextField(blank=True, help_text='Admin notes or feedback on the maintenance request', null=True),
        ),
        migrations.AlterField(
            model_name='historicalmaintenancerequest',
            name='maintenance_type',
            field=models.CharField(choices=[('carpenter', 'Carpenter'), ('aircon', 'Air Conditioning Repair'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roofing', 'Roofing'), ('renovation', 'House Renovation'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('appliance', 'Appliance Repair'), ('structural_repairs', 'Structural Repairs'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='maintenance_type',
            field=models.CharField(choices=[('carpenter', 'Carpenter'), ('aircon', 'Air Conditioning Repair'), ('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('roofing', 'Roofing'), ('renovation', 'House Renovation'), ('painting', 'Painting'), ('flooring', 'Flooring'), ('appliance', 'Appliance Repair'), ('structural_repairs', 'Structural Repairs'), ('other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='MaintenanceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider/Company name', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255, null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Provider address', null=True)),
                ('services', models.TextField(help_text='Comma-separated list of services offered (e.g., plumbing, electrical, roofing)')),
                ('is_nearby', models.BooleanField(default=True, help_text='Is this provider nearby the subdivision?')),
                ('distance', models.CharField(blank=True, help_text="Distance from subdivision (e.g., '2 km', '5 minutes')", max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Is this provider approved by admin?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider currently active?')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Provider rating (0-5)', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this provider', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Provider',
                'verbose_name_plural': 'Maintenance Providers',
                'ordering': ['-is_approved', '-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalMaintenanceProvider',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(help_text='Provider/Company name', max_length=255)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person name', max_length=255, null=True)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254, null=True)),
                ('address', models.TextField(blank=True, help_text='Provider address', null=True)),
                ('services', models.TextField(help_text='Comma-separated list of services offered (e.g., plumbing, electrical, roofing)')),
                ('is_nearby', models.BooleanField(default=True, help_text='Is this provider nearby the subdivision?')),
                ('distance', models.CharField(blank=True, help_text="Distance from subdivision (e.g., '2 km', '5 minutes')", max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Is this provider approved by admin?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this provider currently active?')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, help_text='Provider rating (0-5)', max_digits=3, null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this provider', null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Maintenance Provider',
                'verbose_name_plural': 'historical Maintenance Providers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
