# Generated by Django 4.2.16 on 2025-12-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0064_historicalmaintenancerequest_admin_feedback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisitorrequest',
            name='pin_entered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when PIN was entered at guard station', null=True),
        ),
        migrations.AddField(
            model_name='visitorrequest',
            name='pin_entered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when PIN was entered at guard station', null=True),
        ),
    ]
