"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-uo-ctnd*!(!2z!^5pg$1te=zjdjem@$*58i7@ex^q51o5q#wa!')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Allow all hosts - works for Render, Vercel, and any deployment
# Can be restricted via environment variable if needed
ALLOWED_HOSTS = ['*'] if os.environ.get('ALLOW_ALL_HOSTS', 'True') == 'True' else os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
# Add Render host if RENDER_EXTERNAL_HOSTNAME is set
if os.environ.get('RENDER_EXTERNAL_HOSTNAME'):
    if os.environ.get('RENDER_EXTERNAL_HOSTNAME') not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(os.environ.get('RENDER_EXTERNAL_HOSTNAME'))
# Add any additional hosts from environment
if os.environ.get('ADDITIONAL_ALLOWED_HOSTS'):
    additional_hosts = os.environ.get('ADDITIONAL_ALLOWED_HOSTS').split(',')
    for host in additional_hosts:
        if host.strip() and host.strip() not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host.strip())


# Application definition
 
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt',
    'corsheaders',
    'rest_framework',
    'api',
    'core',
    'simple_history',

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simple_history.middleware.HistoryRequestMiddleware',
]

# Allow all origins for CORS
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# Get frontend URL from environment variable (for reference)
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://happy-homes-frontend.onrender.com')

# CORS allowed origins (not needed when CORS_ALLOW_ALL_ORIGINS = True, but kept for reference)
CORS_ALLOWED_ORIGINS = [
    "https://dc80fc099d37.ngrok-free.app",  # ngrok
    "http://localhost:3000",                 # desktop dev
    "http://127.0.0.1:3000",                 # desktop dev alternate
    "http://192.168.1.100:3000",
]

# Add frontend URL from environment if provided
if FRONTEND_URL not in CORS_ALLOWED_ORIGINS:
    CORS_ALLOWED_ORIGINS.append(FRONTEND_URL)

# CSRF trusted origins - allow all for easier deployment
CSRF_TRUSTED_ORIGINS = [
    "https://dc80fc099d37.ngrok-free.app",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://192.168.1.100:3000",
]

# Add frontend URL to CSRF trusted origins
if FRONTEND_URL not in CSRF_TRUSTED_ORIGINS:
    CSRF_TRUSTED_ORIGINS.append(FRONTEND_URL)


ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
# Using SQLite only - no PostgreSQL

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'  # Philippines timezone

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# WhiteNoise configuration for static files
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST_FRAMEWORK = {
#     'DEFAULT_AUTHENTICATION_CLASSES': (
#         'rest_framework_simplejwt.authentication.JWTAuthentication',
#         # optionally add others like SessionAuthentication
#     ),
#     'DEFAULT_PERMISSION_CLASSES': (
#         'rest_framework.permissions.AllowAny',
        
#     ),
# }

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        'rest_framework.authentication.SessionAuthentication',
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.AllowAny",  # Allow all by default
    ),
    "DEFAULT_PARSER_CLASSES": [
        "rest_framework.parsers.JSONParser",
        "rest_framework.parsers.MultiPartParser",
        "rest_framework.parsers.FormParser",
    ],
}



from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}

# RECAPTCHA_SECRET_KEY = '6Lc7-awrAAAAABrw3hpyIVb7RVwFFkFVozjOwHbT',

# Media files are configured above in Static files section

# --- Email settings (Gmail SMTP) ---
# Gmail is configured and allowed
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')  # Gmail SMTP
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))  # Gmail port
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'  # Gmail requires TLS

# Gmail credentials - use environment variables for production, fallback to defaults
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'happyphhomes@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'hlla ujjd bpjg dfqx')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'Happy Homes <happyphhomes@gmail.com>')

# Optional: destination inbox for contact form notifications
CONTACT_INBOX_EMAIL = os.environ.get('CONTACT_INBOX_EMAIL', DEFAULT_FROM_EMAIL)

# Note: For Gmail to work, you need to:
# 1. Enable "Less secure app access" OR
# 2. Use an App Password (recommended): https://myaccount.google.com/apppasswords
# 3. The password above should be a 16-character App Password, not your regular Gmail password

